# Generated by Django 4.0.1 on 2022-02-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='composer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
