# Generated by Django 4.0.1 on 2022-02-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
